FROM minio/minio:latest

# include mc for bootstrap
COPY --from=minio/mc:latest /usr/bin/mc /usr/bin/mc

COPY minio-entrypoint.sh /usr/local/bin/minio-entrypoint.sh
RUN chmod +x /usr/local/bin/minio-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/minio-entrypoint.sh"]
